# Generated by Django 5.0.2 on 2024-02-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compaints',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=50)),
                ('complaint_details', models.CharField(max_length=500)),
                ('complaint_location', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('working', 'Working'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('reason', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
