# Generated by Django 5.0.2 on 2024-02-27 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaints',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
