# Generated by Django 5.0.2 on 2024-11-03 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Complaints', '0002_compaints_created_date'),
        ('User', '0003_rename_is_active_official_head_of_wing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('complaint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('complaint_details', models.CharField(max_length=500)),
                ('complaint_location', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('working', 'Working'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('wing', models.CharField(choices=[('national_highway', 'National_Highway'), ('road', 'Road'), ('buildings', 'Buildings'), ('bridges', 'Bridges')], max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='User.user')),
                ('person_assigned', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, related_name='Official_name', to='User.official')),
            ],
        ),
        migrations.DeleteModel(
            name='Compaints',
        ),
    ]
